### ISSUE TITLE
Naming convention and coding style

### ISSUE THREAD

**Issue by fizruk** [emilyriehl/yoneda#10]
Here are some potentially relevant naming conventions in other proof assistant libraries:
1. For Agda's stdlib: https://github.com/agda/agda-stdlib/blob/master/notes/style-guide.md
2. For Coq-HoTT library: https://github.com/HoTT/Coq-HoTT/blob/master/STYLE.md#1-conventions-and-style-guide
3. A more general style guide for Coq: https://vstyle.readthedocs.io/en/latest/
4. Mathlib naming conventions for Lean 3: https://leanprover-community.github.io/contribute/naming.html#general-conventions

We have also had some discussion in #9, which I will replicate here:

> I think we have briefly considered several code styles and were leaning towards [Coq-HoTT code style](https://github.com/HoTT/Coq-HoTT/blob/master/STYLE.md#1-conventions-and-style-guide).
However, we did not yet take any steps towards formatting and renaming existing code.
Perhaps, we should do that in a separate PR, applying to the entire codebase.
> 
> _Originally posted by @fizruk in https://github.com/emilyriehl/yoneda/issues/9#issuecomment-1586246355_

> I should say, I'm clearly partial to `agda-unimath`, but I do believe its style conventions would benefit this project. Particularly since some of the code used in this project is derived from it. And also, for instance, I don't see why it should be necessary to write comments in the code at all, as you're using a literate format.
> 
> _Originally posted by @fredrik-bakke in https://github.com/emilyriehl/yoneda/issues/9#issuecomment-1586362921_
            
> Hey! Sorry to be so slow to weigh in. I've been crisscrossing the UK on trains with terrible wifi. 
> 
> Regarding the naming/commenting conventions, I agree it's time to make clearer style conventions. Fredrik could you say a bit more about what you prefer about agda-unimath to Coq-HoTT? I'm open to being persuaded. 
> 
> Regarding the commenting, I agree that the comments we've been using on arguments, eg the annotations on the variables p and q below, aren't so useful. 
> 
> ```rzk
> -- path composition by induction on the second path
> #def concat
>   (p : x = y)       -- A path from x to y in A.
>   (q : y = z)       -- A path from y to z in A.
>   : (x = z)
>   := idJ(A, y, \z' q' -> (x = z'), p, z, q)
> 
> -- an alternative construction of path composition by induction on the first path
> -- this is useful in situations where it's easier to induct on the first path
> #def altconcat
>   (p : x = y)       -- A path from x to y in A.
>   : (y = z) -> (x = z)
>   := idJ(A, x, \y' p' -> (y' = z) -> (x = z), \q' -> q', y, p)
> ```
> But  I do like the comments before the definitions that explain the main idea. Did you object to those as well?
> 
> _Originally posted by @emilyriehl in https://github.com/emilyriehl/yoneda/issues/9#issuecomment-1587509428_

**Comment by fizruk** [comment]
My 2 cents regarding code comments:

1. Argument comments may be used by IDE to (better) explain what is expected in some hole. They are also useful for beginners who need periodic reminders even for simple arguments like `(p : x = y)`. I agree though that some descriptions are straightforward and, perhaps, can be automatically generated or revealed on demand.

2. I think code comment/annotation preceding the definition is supposed to be like a figure/listing caption in a paper. This is in contrast to a detailed description or a reference in the main text. So I am in favour of keeping both.

**Comment by fredrik-bakke** [comment]
I'll paste this here in the meantime:

> Thanks! I'll try and make a case tomorrow. Perhaps the main points I'd like to get across is that I think your comments should just be written out in prose outside of the coding environment instead. The other use case for comments, i.e. as annotations, should be very small with a good enough naming and style convention and is also something one generally wants little of in other comparable media like on wikis and in articles. In my experience, contributing to agda-unimath, I've never once found a need to comment on my code inside of the coding environment.

**Comment by fredrik-bakke** [comment]
As a direct response to your question yesterday, I would much rather format it as follows than having comments in the code:

> We define path composition by induction on the second path as follows.
> ```rzk
> #def concat
>   (p : x = y)
>   (q : y = z)
>   : (x = z)
>   := idJ(A, y, \z' q' -> (x = z'), p, z, q)
> ```
> 
> There is also an alternative construction of path composition by induction on the first path. This is useful in situations where it's easier to induct on the first path:
> 
> ```rzk
> #def altconcat
>   (p : x = y)
>   : (y = z) -> (x = z)
>   := idJ(A, x, \y' p' -> (y' = z) -> (x = z), \q' -> q', y, p)
> ```

**Comment by fizruk** [comment]
I have looked at the [Library coding style for agda-unimath](https://unimath.github.io/agda-unimath/CODINGSTYLE.html). Indeed, I like what I see there a lot. I would probably adjust a few minor things for Rzk, but generally, it looks great and I agree that a good coding style for Agda fits Rzk more than a coding style for Coq.

Also I do not quite understand yet, how to properly rename some definitions, e.g. those in https://emilyriehl.github.io/yoneda/simplicial-hott/05-segal-types.rzk/
Perhaps, there needs to be an extra convention for referring to the use of shapes in the type of a definition.

@fredrik-bakke can you say how much of these, if any, are enforced by IDE tools/extensions?

**Comment by fredrik-bakke** [comment]
Oh excuse me, I should have provided a link as well. 😅 I'm glad you like it though! And yeah I expect some things will need to be adjusted. For instance, I quite like your choice of starting the final line in a type signature with `:` as opposed to ending the previous line with it, which would be the way to do it in `agda-unimath`.

To answer your question, the naming conventions themselves are only enforced by humans. Some of the formatting is done automatically, though not much with regard to the Lisp-like convention.

Let me see if I can suggest some names for `05-segal-types` for you:

- `hom` -> `hom`
- `hom2` -> `hom2`
- `isSegal` -> `is-segal` (and then I would also define the Sigma type `Segal` and make additional definitions later where appropriate)
- `Segal-comp` -> `hom-comp-is-segal` (and `hom-comp-Segal`)(I realized on second inspection this should probably be  the name to accommodate the next constructions, and because `comp-is-segal` reads more naturally as the full composition term)
- `Segal-comp-witness` -> `is-comp-hom-comp-is-segal`
- `Segal-comp-uniqueness` -> `unique-hom-comp-is-segal` (`is-contr-comp-is-segal` would just be the Segal condition itself)
- `horn` -> `hom-horn` perhaps?
- `horn-restriction` -> `restrict-horn` (or `precomp-horn-inclusion`)
- `isSegal'` -> `is-segal'` (you could also consider naming it the more descriptive `is-local-horn-inclusion`)
- `compositions-are-horn-fillings` -> `equiv-horn-filling-composition` (I prefer the name `equiv` for the type of equivalences. `Eq` is too easy to confuse with equality.)
- `restriction-equiv` -> `equiv-tot-horn-filling-2-simplex` (not entirely convinced by this one)
- `Segal-restriction-equiv` -> `equiv-horn-filling-2-simplex-is-segal`
- `Segal-function-types` -> `is-segal-function-type-is-segal` (and `function-type-Segal`, the latter would presumably assume that the domain is Segal as well)
- `Segal-extension-types` -> `is-segal-extension-type-is-segal` (and `extension-type-Segal`)

I agree that some of these names are a bit awkward. Especially the ones involving the 2-simplex. Feel free to suggest other names as well :)

**Comment by emilyriehl** [comment]
Thanks for this discussion. It seems we're converging on a convention, which is mostly agda-unimath-like with some exceptions (like the placement of the colon on the same line of the type the term we are defining belongs to).

I have a few remaining questions:

(i) Regarding @fredrik-bakke's reference to move most in text comments outside the code blocks, is this compatible with sections? See for example the comments in the code in the section "Coherence data from an invertible map" of "Equivalences". I'm still in agreement with @fizruk that it can be useful to include some comments in sections.

(ii) Where should literature references be placed? Not in section titles, certainly, but on this point I'm open to either having them inside or outside the code blocks.

(iii) Is there any way to make names any shorter? Eg could you elaborate on your preference for "hom-comp-is-segal" over "comp-is-segal"? I'd be in favor, generally, of deviating from the conventions slightly for names we use over and over again.

(iv) The terms I found the hardest to names were auxiliary paths/equalities or equivalences constructed in a long proof. I realize in other libraries these might not be given as separate definitions at all, but in rzk it's harder to know where you are in the midst of writing a proof, so if I'm ultimately going to need to compose 12 paths, I'd rather just define the 12 paths first. For an example of this, see the proof that in the sectino "Half adjoint equivalences are contractible" in "Fibers". What should these terms have been called?

**Comment by fredrik-bakke** [comment]
Let me try to answer your questions.

(i) To my limited understanding, what happens when a literate file is typechecked is that the markdown code is discarded, so it will be treated like it is not even there. This means that a section will remain open until it is explicitly closed in the code, even if that is in a later code block. Thus, you can exit a code block to insert prose even without terminating your current rzk section.

When it comes to the idea that comments should be unnecessary, I don't feel like I've given you the entire story, so maybe another example could be enlightening. For instance, the following is your current section defining invertible maps:
````md
## Invertible maps

```rzk
-- the following type of more coherent equivalences is not a proposition
#def hasInverse
    (A B : U)
    (f : A -> B)
    : U
    := ∑ (g : B -> A),    -- A two-sided inverse
        (prod
            (homotopy A A (composition A B A g f)(identity A))    -- The retracting homotopy
            (homotopy B B (composition B A B f g)(identity B)))   -- The section homotopy
```
````
The first comment here, I think is easy to pull out of the code block, and it would perhaps not be so controversial to do so. However, the other comments in this code carry extra information that I assume you want to keep. My view, however, is that this should not just be information carried by comments, but information carried by the code. I probably don't want to have to remember which projection to use for the retracting homotopy and which to use for the section homotopy. Instead, I would want to write:
````md
## Invertible maps

An **invertible map** is a map `f : A → B` eqiupped with the _structure_ of a
two-sided inverse, i.e. a map `g : B → A` that is both a retraction and a
section of `f`. Such a structure is not in general a proposition.

```rzk
#def is-invertible
    (A B : U)
    (f : A -> B)
    : U
    :=
      Σ ( g : B -> A) ,
        ( prod
          ( homotopy A A (composition A B A g f) (identity A))
          ( homotopy B B (composition B A B f g) (identity B)))
```

### Invertibility data

```rzk
#def map-inv-is-invertible
    (A B : U)
    (f : A -> B)
    (is-invertible-f : is-invertible A B f)
    : B -> A
    := first is-invertible-f

#def is-section-is-invertible
    (A B : U)
    (f : A -> B)
    (is-invertible-f : is-invertible A B f)
    : homotopy A A
        ( composition A B A (map-inv-is-invertible A B f is-invertible-f) f)
        ( identity A)
    := first (second is-invertible-f)

#def is-retraction-is-invertible
    (A B : U)
    (f : A -> B)
    (is-invertible-f : is-invertible A B f)
    : homotopy B B
        ( composition B A B f (map-inv-is-invertible A B f is-invertible-f))
        ( identity B)
    := second (second is-invertible-f)
```
````
This way, I can refer to the retracting homotopy by name, instead of by position.

**Comment by fredrik-bakke** [comment]
(ii) I'm not so sure about this. To be honest, I would be fine with having these as code comments, but it would probably look better as part of the markdown. How they would look best, however, I don't know.

**Comment by emilyriehl** [comment]
Thanks for this illustrative example. I like this style in general but I've found the auxiliary functions a bit less practical to use without implicit arguments. It's much shorter to write "first second is-invertible-f" then to write is-section-is-invertible A B f is-invertible-f" but of course the latter is more readable which is the more important thing.

**Comment by fredrik-bakke** [comment]
(iii) I agree that the code can become somewhat verbose, but I am not convinced that should be a large concern. To [quote Egbert](https://unimath.github.io/agda-unimath/CODINGSTYLE.html):
> Our naming conventions are not to ensure the shortest possible names, and neither to ensure the least amount of typing by the implementers of the library, but to display as accurately as possible what concepts are applied, and hence improve the readability.

Of course, constructions known best by special names should usually be given those names, and if you want more terse names, I don't have very much against that.

The reason that I changed preference to `hom-comp-is-segal` is because, to me, `comp-is-segal` reads more naturally as giving a term of type
```rzk
Σ (h : hom A x z) , (hom2 A x y z f g h)
```
i.e. a "composition term", as opposed to the `hom` of this term, i.e. the first projection. This, moreover, makes the formulation `is-comp-hom-comp-is-segal` make sense in terms of actual definitions, where `is-comp` is taken to mean a term of type `hom2`.

Another comparable example would be the triple `Segal`, `type-Segal`, and `is-segal-type-Segal`. This is a pattern we see all the time over at `agda-unimath`, e.g. [here](https://unimath.github.io/agda-unimath/foundation-core.propositions.html#845). So keeping this convention rigid helps keep the code base navigatable. But again, I am not particularly against breaking the pattern for segal composites.

**Comment by fredrik-bakke** [comment]
(iv) For technical lemmas like this, where the chance they will be reused is low, I don't think the particular names matter that much. Again, you may find the original naming scheme I outlined somewhat useful. I'm astonished that you need to concatenate twelve paths though. If it helps, `agda-unimath` has a proof of this fact [here](https://unimath.github.io/agda-unimath/foundation-core.coherently-invertible-maps.html#invertible-maps-are-coherenctly-invertible), although I assume you have already looked at this.

**Comment by fizruk** [comment]
> > Thanks for this illustrative example. I like this style in general but I've found the auxiliary functions a bit less practical to use without implicit arguments. It's much shorter to write "first second is-invertible-f" then to write is-section-is-invertible A B f is-invertible-f" but of course the latter is more readable which is the more important thing.
> 
> This is an unfortunate consequence of not having implicit arguments.

Please, correct me if I'm wrong, but it seems that `let`-expressions (https://github.com/fizruk/rzk/issues/23) or (perhaps better) `where`-blocks should help with auxiliary definitions more than implicit arguments. They should also be much easier to add to the language. That said, I do plan to add implicit arguments in Rzk.

**Comment by emilyriehl** [comment]
In light of this discussion, I'd be happy to move forward with the agda-unimath naming conventions, but with a minor tweak to the formatting (in the position of the colon). I'd prefer to continue to experiment with comments both in and out of the code blocks. I think as things evolve later we may settle on a preference for one style over another.

@fizruk do you have any further suggestions or objections? If not, then @fredrik-bakke would you draft a style guide file for us to use (adopted from the one you've used already)?

**Comment by fredrik-bakke** [comment]
Sure, I can do this! I'm quite busy at the moment, but I can try and find the time in the second half of next week.

**Comment by fredrik-bakke** [comment]
I'm sorry, I've been preoccupied with other things and haven't had the time to work on this. I will find the time next week if it is not time critical for you.

**Comment by fizruk** [comment]
I think there is no rush. If I get to it sooner (this week(end)), I will let you know.

**Comment by emilyriehl** [comment]
Yes, no problem at all. Sorry to have put this on your plate, but it seemed to me that with your experience you'd do this best ;)

**Comment by fredrik-bakke** [comment]
Don't get me wrong, I would still love to do this! I just haven't had the surplus energy and time. I appreciate that you are involving me.
