### ISSUE TITLE
Reopened dependent Yoneda branch

### ISSUE THREAD

**Issue by jonweinb** [emilyriehl/yoneda#22]
I am sorry for closing it too early, see here:
https://github.com/emilyriehl/yoneda/pull/21

**Comment by emilyriehl** [comment]
Not a big deal at all. (And actually it's not clear to me what reopening a merged branch does? I think it's still merged.)

Personally I like the collaborative aspect of using pull requests because it makes it easy for everyone to comment on new code before it's officially merged. But of course we can always revise the code after merging instead so it really doesn't matter.

**Comment by emilyriehl** [comment]
I'm going to close this issue but we can discuss further if you like.
