### ISSUE TITLE
Switch to Unicode syntax

### ISSUE THREAD

**Issue by fizruk** [emilyriehl/yoneda#29]
Rzk supports Unicode syntax since v0.5.2 (see https://github.com/rzk-lang/rzk/pull/61#issue-1787906295).
We already use Unicode for Sigma-types, so I think it makes sense to use more of it :)

Perhaps, we should update the style guide as well.

**Comment by emilyriehl** [comment]
I tried to switch all the \/ and /\'s to the unicode versions a month or so ago and hand compilation issues. Are you saying this is fixed now?

FYI there's a problem with my python installation on my computer (it can't find apt_pkg or update-notifier-common, update-notifier, and update-manager needed for dpkg and without these I can't seem to (re)install anything) so I'm still typechecking using the cloned repository version of rzk rather than the new vscode extension.

**Comment by fizruk** [comment]
Yes, Unicode is now fixed, see [here](https://github.com/rzk-lang/rzk/pull/61#issue-1787906295) the list of supported symbols.

I'm not sure how Python affects VS Code extensions, I think they are pretty independent. Do you have VS Code working? Do you have the [rzk extension](https://github.com/rzk-lang/vscode-rzk) installed (updated)? If yes, then everything should work out of the box.
