### ISSUE TITLE
Check and render STYLEGUIDE.md

### ISSUE THREAD

**Issue by fizruk** [emilyriehl/yoneda#32]
Currently `STYLEGUIDE.md` is not checked with `rzk` and is not rendered with MkDocs.

**Comment by emilyriehl** [comment]
Would this work even if we include examples in the style guide that depend on terms defined elsewhere?

**Comment by fredrik-bakke** [comment]
I don't think the styleguide should be type checked. It is supposed to contain example code for demonstration, not actual formalizations. For instance, it would be natural to have copies of constructs defined elsewhere there, and this will introduce naming conflicts if type checked.

**Comment by fizruk** [comment]
Here's why I think the styleguide should be checked:

1. It is good to make sure examples are valid.
2. Since `rzk`'s syntax is still evolving, it is good to keep styleguide up-to-date, updating from any deprecated syntax.
3. Since we want to copy constructs defined elsewhere as examples, we want these constructs to also be up-to-date: if we rename some definitions in the main formalisation files, we want their mentions in the styleguide to also be updated.
4. For the name conflicts, it is easy to just add some option(s) to allow shadowing top-level definitions and (imported) definitions from other files. So in the styleguide we would just have something like

    ```rzk
    #lang rzk-1

    #set-option "warn-imported-name-shadowing"  = "silent"  -- default: "error"
    #set-option "warn-top-level-name-shadowing" = "silent"  -- default: "error"
    ```

**Comment by fredrik-bakke** [comment]
Alright, then I don't see anything principally wrong with your suggestion, and think it can be implemented.

There are still some things I would like to address:
- The extra pragmas can be hidden with an XML details block to avoid cluttering the guide.
- Would you consider supporting a code block attribute to bypass the type checker, so that we can have incomplete code with syntax highlighting as well?
- Will you resolve the loading order by always loading the styleguide last?
