### ISSUE TITLE
Unification error for sigma types

### ISSUE THREAD

**Issue by jonweinb** [emilyriehl/yoneda#5]
In 4-equivalences.rzk, when replacing line 506
` (\u -> \v -> (refl-in-Sigma A B u v))`
by
`(\u -> \v -> (refl_{u}, refl_{v}))`
I'm getting the following error:
`  Error occurred when checking`
   ` #def reflexive-Eq-Sigma`

`cannot unify term`
 ` idJ (A, first (u, v), \ (y' : A) -> \ (p' : first (u, v) =_{ A } y') -> B y', second (u, v), first (u, v), p)`
`with term`
  `v`

**Comment by fizruk** [comment]
It seems that this issue refers to a previous version of the code:

https://github.com/emilyriehl/yoneda/blob/1c9111d0be05f9ebc85cd8a56bd7cc747aeca7d4/hott/4-equivalences.rzk#L494-L507

Is it still a problem with `rzk-0.2.0`?

**Comment by jonweinb** [comment]
Seems it still is: Replacing line 50 in 5-sigma.md with
`(\u v -> (refl-in-Sigma A B u v))`
gives the same error (even when annotating the transport in refl-in-Sigma with its type B x).

**Comment by fizruk** [comment]
I'm sorry, I missed this message.

I've looked at the code, the problem is with the definition of `refl-in-Sigma`. Here is the necessary fix:

```diff
 -- [Rijke 22, used in Lemma 9.3.2]
 #def refl-in-Sigma
     (A : U)
     (B : A -> U)
     (x : A)
     (y : B x)
-    : ∑(p : (x = x)), ((transport A B x x refl_{x} y) = y)
+    : ∑(p : (x = x)), ((transport A B x x p y) = y)
     := (refl_{x}, refl_{y})
```

The problem is that `refl_{x}` is used in the type, when it should be `p`. That is, the current type is too specific, so you cannot use it when you define `reflexive-Eq-Sigma`. Note the error message:

```
...
when typechecking
  refl-in-Sigma A B u v
against type
  (\ (k : Sigma (a : A), B a) -> Eq-Sigma A B k k) (u, v)

when unifying expected type
  Sigma (p : first (u, v) =_{ A } first (u, v)), transport A B (first (u, v)) (first (u, v)) p (second (u, v)) =_{ B (first (u, v)) } second (u, v)
with actual type
  Sigma (p : u =_{ A } u), transport A B u u refl_{ u : A } v =_{ B u } v
for term
  refl-in-Sigma A B u v

when unifying term
  transport A B (first (u, v)) (first (u, v)) p (second (u, v)) =_{ B (first (u, v)) } second (u, v) : U
with term
  transport A B u u refl_{ u : A } v =_{ B u } v : U

when unifying term
  transport A B (first (u, v)) (first (u, v)) p (second (u, v)) : B (first (u, v))
with term
  transport A B u u refl_{ u : A } v : B u

Local tope context:
  TOP

src/hott/5-sigma.md:
  Error occurred when checking
    #define reflexive-Eq-Sigma

cannot unify term
  idJ (A, first (u, v), \ (y' : A) -> \ (p' : first (u, v) =_{ A } y') -> B y', second (u, v), first (u, v), p)
with term
  v
```

You can see that `rzk` expects `p` where `refl_{ u : A}` is given. Of course, `transport` applied to `refl` is computed to `v`, so the final error message is a bit misleading here.

I'm not yet sure how to improve the error message here, but it is a good example!
